spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fjserp
    username: root
    password: 1234
mybatis-plus:
  type-aliases-package: com.fjs.erp.datasource.mappers
  global-config:
    db-config:
      id-type: auto